from PEC/PKCS8 to PKCS12, add also a bit more logging

diff --git a/azure-pipelines.yaml b/azure-pipelines.yaml
--- a/azure-pipelines.yaml
+++ b/azure-pipelines.yaml
@@ -27,21 +27,23 @@ stages:
                 if [ ${{ parameters.force_renew_cert }} == "True" ]
                 then
                   echo "##vso[task.setvariable variable=require_new_certificate;isOutput=true]True"
+                  echo "Parameter force_renew_cert is set to true"
                   exit 0
                 fi
-                if ! az keyvault certificate download --vault-name '$(KEY_VAULT_NAME)' -n '$(KEY_VAULT_CERT_NAME)' -f certificate.pem >/dev/null
+                if ! az keyvault certificate download --vault-name '$(KEY_VAULT_NAME)' -n '$(KEY_VAULT_CERT_NAME)' -f certificate.pfx >/dev/null
                 then
                   echo "##vso[task.setvariable variable=require_new_certificate;isOutput=true]True"
+                  echo "The certificate was not found in the selected keyvault"
                   exit 0
                 else
-                  if ! openssl x509 -checkend '$(CERT_NAME_EXPIRE_SECONDS)' -noout -in certificate.pem >/dev/null 2>&1
+                  if ! openssl x509 -inform pem -checkend '$(CERT_NAME_EXPIRE_SECONDS)' -noout -in <(openssl pkcs12 -in certificate.pfx -clcerts -passin pass: -passout pass: 2>/dev/null)
                   then
                     # certificate is expiring or is already expired
                     echo "##vso[task.setvariable variable=require_new_certificate;isOutput=true]True"
                   fi
                 fi
 
-          - script: rm -f certificate.pem
+          - script: rm -f certificate.pfx
             name: CleanupRenewalDecision
             condition: eq(${{parameters.force_renew_cert}}, False)
 
@@ -95,8 +97,8 @@ stages:
               scriptType: bash
               scriptLocation: inlineScript
               inlineScript: |
-                cat csr.key >> certificate_chain.pem
-                az keyvault certificate import --vault-name '$(KEY_VAULT_NAME)' -n '$(KEY_VAULT_CERT_NAME)' --disabled false -f certificate_chain.pem >/dev/null
+                openssl pkcs12 -inkey csr.key -in certificate_chain.pem -export -passout pass: -nodes -out certificate_chain.pfx
+                az keyvault certificate import --vault-name '$(KEY_VAULT_NAME)' -n '$(KEY_VAULT_CERT_NAME)' --disabled false -f certificate_chain.pfx --password "" >/dev/null
 
           - task: Bash@3
             name: CleanupEverything
@@ -109,3 +111,4 @@ stages:
                 rm -f csr.der
                 rm -f csr.key
                 rm -f certificate_chain.pem
+                rm -f certificate_chain.pfx
